sonar.projectKey=TheMicStudio_EsieeToutCommence
sonar.organization=themicstudio

sonar.projectName=Hub École
sonar.projectVersion=1.0

# Sources analysées
sonar.sources=src
sonar.exclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,node_modules/**,.next/**

# TypeScript
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8

# Qualité minimum (Quality Gate)
sonar.qualitygate.wait=true
